.github/workflows/ci.yml, README.md, mkdocs_include_markdown_plugin/event.py, mkdocs_include_markdown_plugin/process.py, tests/test_include_markdown.py, tests/test_process.py
Fix #1
- Add processing code to translate relative paths
- Integrate with the directive and add integration test
=> rewrite relative urls

.bumpversion.cfg, mkdocs_include_markdown_plugin/__init__.py, mkdocs_include_markdown_plugin/event.py, setup.cfg, tests/test_nested_includes.py
=> Make heading-offset cumulative over nested inclusions

.bumpversion.cfg, mkdocs_include_markdown_plugin/__init__.py, mkdocs_include_markdown_plugin/process.py, setup.cfg, tests/test_process.py
=> Don't rewrite relative links inside codeblocks

examples/frontmatters/docs/bad-multimarkdown.md, examples/frontmatters/docs/bad-yaml.md, examples/frontmatters/docs/good-multimarkdown.md, examples/frontmatters/docs/good-yaml.md, examples/frontmatters/docs/index.md, examples/frontmatters/mkdocs.yml
=> Add example including from files with frontmatters

.bumpversion.cfg, .pre-commit-config.yaml, examples/basic/docs/included.md, examples/basic/docs/index.md, examples/basic/mkdocs.yml, mkdocs_include_markdown_plugin/__init__.py, mkdocs_include_markdown_plugin/event.py, setup.cfg, tests/test_include_markdown.py
=> Wrap start and end delimiters in comments

pyproject.toml, src/mkdocs_include_markdown_plugin/plugin.py
=> Fix LiveReloadServer not imported at runtime

.pre-commit-config.yaml
Upgrades revisions of pre-commit hooks tools to latest versions :hammer_and_wrench:
=> Upgrade pre-commit hooks revisions

.pre-commit-config.yaml, locale/es/README.md, locale/fr/README.md, pyproject.toml, src/mkdocs_include_markdown_plugin/plugin.py
=> Fix error using livereload server with Mkdocs < 1.4.0

.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, src/mkdocs_include_markdown_plugin/event.py
=> Drop Python3.7 support

.github/workflows/ci.yml, .gitignore, .pre-commit-config.yaml, pyproject.toml, src/mkdocs_include_markdown_plugin/__init__.py, src/mkdocs_include_markdown_plugin/cache.py, src/mkdocs_include_markdown_plugin/config.py, src/mkdocs_include_markdown_plugin/directive.py, src/mkdocs_include_markdown_plugin/event.py, src/mkdocs_include_markdown_plugin/files_watcher.py, src/mkdocs_include_markdown_plugin/plugin.py, src/mkdocs_include_markdown_plugin/process.py, tests/conftest.py, tests/test_integration/test_cache_integration.py, tests/test_integration/test_examples.py, tests/test_unit/test_arguments.py, tests/test_unit/test_config.py, tests/test_unit/test_encoding.py, tests/test_unit/test_exclude.py, tests/test_unit/test_glob_include.py, tests/test_unit/test_include.py, tests/test_unit/test_include_markdown.py, tests/test_unit/test_logging.py, tests/test_unit/test_nested_includes.py, tests/test_unit/test_process.py, tests/testing_helpers.py
=> Drop Python upper version bound and migrate dev tools to Ruff

pyproject.toml, src/mkdocs_include_markdown_plugin/event.py, tests/test_unit/test_glob_include.py, tests/test_unit/test_include.py, tests/test_unit/test_include_markdown.py, tests/test_unit/test_logging.py, tests/test_unit/test_nested_includes.py
Fixes #183, regression from [v6.0.2](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v6.0.2).
=> Fix logging variables not included formatting messages

.pre-commit-config.yaml, README.md, locale/es/README.md, locale/es/README.md.po, locale/fr/README.md, locale/fr/README.md.po, pyproject.toml
Also updates tooling dependencies.
=> Fix links in READMEs translations

.pre-commit-config.yaml, pyproject.toml, src/mkdocs_include_markdown_plugin/event.py
=> Fix default `heading_offset` setting not being applied

pyproject.toml, src/mkdocs_include_markdown_plugin/event.py
Rationale explained at https://github.com/mondeja/mkdocs-include-markdown-plugin/pull/208#discussion_r1619477020
=> Change substitutions order of directives

README.md, locale/es/README.md, locale/fr/README.md, pyproject.toml, src/mkdocs_include_markdown_plugin/directive.py, src/mkdocs_include_markdown_plugin/event.py, src/mkdocs_include_markdown_plugin/logger.py, src/mkdocs_include_markdown_plugin/process.py, tests/test_unit/test_arguments.py, tests/test_unit/test_exclude.py, tests/test_unit/test_glob_include.py, tests/test_unit/test_include.py, tests/test_unit/test_nested_includes.py
=> Warn when passing invalid arguments to directives

src/mkdocs_include_markdown_plugin/event.py
=> Apply substitutions from all directives at once

.github/workflows/ci.yml, src/mkdocs_include_markdown_plugin/process.py, tests/test_unit/test_process.py
=> Indented code blocks only when surrounded by newlines

.gitignore, src/mkdocs_include_markdown_plugin/cache.py, src/mkdocs_include_markdown_plugin/directive.py, src/mkdocs_include_markdown_plugin/event.py, src/mkdocs_include_markdown_plugin/plugin.py, src/mkdocs_include_markdown_plugin/process.py
=> Improve performance

examples/include-if-exists/docs/included.md, examples/include-if-exists/docs/index.md, examples/include-if-exists/mkdocs.yml
Related to #228 and https://github.com/mondeja/mkdocs-include-markdown-plugin/discussions/242
=> Add example including file only if exists

pyproject.toml, src/mkdocs_include_markdown_plugin/directive.py, src/mkdocs_include_markdown_plugin/event.py, src/mkdocs_include_markdown_plugin/process.py, tests/test_unit/test_include_markdown.py
=> Fix negative heading-offset
